# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.9"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Tag a build on GitHub"
  lane :tag do
    current_date = Time.now.strftime("%Y_%m_%d")
    new_version = get_version_number
    new_tag = current_date + "_v" + new_version
    # sh "git tag -d #{new_tag}"
    add_git_tag(tag: new_tag)
    # sh "git push origin :#{new_tag}"
    sh "git push origin HEAD:master --tags"
  end

  lane :testVersion do

    new_version = set_new_version()
    release_branch = ENV['HELLO']
      message = "Increment version number to #{new_version} .[skip ci]"
      commit_new_version(message, ENV['HELLO'])

      # reflect version number on develop
      sh "git checkout develop"
      sh "git pull origin develop"
      increment_version_number(version_number: new_version)
      commit_new_version(message, "develop")

       sh "git checkout #{release_branch}"
  end

  def commit_new_version(message, branch)
    sh "git add ../${PROJECT}/Info.plist"    
    sh "git add ../${PROJECT}UITests/Info.plist" 
    sh "git add ../${PROJECT}.xcodeproj/project.pbxproj"
    sh "git commit -m \"#{message}\""
    sh "git push origin HEAD:#{branch}"
  end


  def set_new_version()
    last_tag_version = last_git_tag
    current_version = ENV['HELLO']
    version_array = current_version.split('/')[-1].split('.')

    new_version = 0
    minor_version = 0

    unless last_tag_version.nil?
      last_tag_version_array = last_tag_version.split('v')[-1].split('.')

      for i in 0..2
        if (version_array[i].to_i < last_tag_version_array[i].to_i)
          version_array = last_tag_version_array
          minor_version = version_array[-1].strip.to_i
          minor_version += 1
          break
        elsif version_array[i].to_i > last_tag_version_array[i].to_i
          minor_version = version_array[-1].strip.to_i
          break
        end
      end

      check = false
      for i in 0..2
        if (version_array[i].to_i == last_tag_version_array[i].to_i)
          check = true
        elsif version_array[i].to_i != last_tag_version_array[i].to_i
          check = false
          break
        end
      end

      if check == true
        version_array = last_tag_version_array
        minor_version = version_array[-1].strip.to_i
        minor_version += 1
      end

    else
      minor_version = version_array[-1].strip.to_i
    end

    version_array[-1] = minor_version
    new_version = version_array.join(".")

    increment_build_number
    increment_version_number(version_number: new_version)

    return new_version
  end

  #hehehehe

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
